import { MSG } from "@/constants/string";

export const TOOLTIP_IDS = {
  ANALYSIS_REQUEST_REVIEW: "analysisRequestReview",
  ANALYSIS_CDM_REGISTER: "analysisCdmRegister",
  ANALYSIS_CDM_REVIEW: "analysisCdmReview",
  ANALYSIS_ORG_REGISTER: "analysisOrgRegister",
  ANALYSIS_ORG_REVIEW: "analysisOrgReview",
  ANALYSIS_META_REGISTER: "analysisMetaRegister",
  ANALYSIS_DATASET_REGISTER: "analysisDATASETRegister",
  ANALYSIS_DATASET_REQUEST_REVIEW: "analysisDatasetRequestReview",
  ANALYSIS_REVIEW_REGISTER: "analysisReviewRegister",
} as const;

export type TooltipId = (typeof TOOLTIP_IDS)[keyof typeof TOOLTIP_IDS];

export const TOOLTIP_CONTENT: Record<TooltipId, string> = {
  [TOOLTIP_IDS.ANALYSIS_REQUEST_REVIEW]: MSG.ANALYSIS_REQUEST_REVIEW,
  [TOOLTIP_IDS.ANALYSIS_CDM_REGISTER]: MSG.TOOLTIP_CDM_REGISTER,
  [TOOLTIP_IDS.ANALYSIS_CDM_REVIEW]: MSG.TOOLTIP_CDM_REVIEW,
  [TOOLTIP_IDS.ANALYSIS_ORG_REGISTER]: MSG.TOOLTIP_ORG_REGISTER,
  [TOOLTIP_IDS.ANALYSIS_ORG_REVIEW]: MSG.TOOLTIP_ORG_REVIEW,
  [TOOLTIP_IDS.ANALYSIS_META_REGISTER]: MSG.TOOLTIP_META_REGISTER,
  [TOOLTIP_IDS.ANALYSIS_DATASET_REGISTER]: MSG.TOOLTIP_DATASET_REGISTER,
  [TOOLTIP_IDS.ANALYSIS_DATASET_REQUEST_REVIEW]: MSG.TOOLTIP_DATASET_REQUEST_REVIEW,
  [TOOLTIP_IDS.ANALYSIS_REVIEW_REGISTER]: MSG.TOOLTIP_REVIEW_REGISTER,
};
