/** `/researches` 하위 경로. 파일·UUID 등은 호출부에서 encodeURIComponent 처리 후 전달. */

const R = "/researches";

export const researchApiPaths = {
  adminList: () => `${R}/admin`,
  partnerList: () => `${R}/partner`,
  researchById: (id: number) => `${R}/${id}`,
  researchesRoot: () => R,
  researchByAsmtSn: (asmtSn: number) => `${R}/${asmtSn}`,
  status: (asmtSn: number) => `${R}/${asmtSn}/status`,
  close: (asmtSn: number) => `${R}/${asmtSn}/close`,
  cancel: (asmtSn: number) => `${R}/${asmtSn}/cancel`,
  partners: (asmtSn: number) => `${R}/${asmtSn}/partners`,
  partnerBySn: (asmtSn: number, asmtPtcpInstSn: string | number) => `${R}/${asmtSn}/partners/${asmtPtcpInstSn}`,
  inviteByInst: (asmtSn: number, instId: number) => `${R}/${asmtSn}/partners/${instId}/invite`,
  inviteByPtcp: (asmtSn: number, asmtPtcpInstSn: number | string) => `${R}/${asmtSn}/partners/${asmtPtcpInstSn}/invite`,
  analysisData: (asmtSn: number) => `${R}/${asmtSn}/analysis-data`,
  orgAnalysisData: (asmtSn: number) => `${R}/${asmtSn}/analysis-data/org-analysis-data`,
  analysisDataBySn: (asmtSn: number, asmtMetaRsltSn: number) => `${R}/${asmtSn}/analysis-data/${asmtMetaRsltSn}`,
  analysisDataLatest: (asmtSn: number) => `${R}/${asmtSn}/analysis-data/latest`,
  analysisDataStatus: (asmtSn: number, asmtMetaRsltSn: number) => `${R}/${asmtSn}/analysis-data/${asmtMetaRsltSn}/status`,
  reviewRequest: (asmtSn: number, asmtMetaRsltSn: number) => `${R}/${asmtSn}/analysis-data/${asmtMetaRsltSn}/review-request`,
  reviewClose: (asmtSn: number, asmtMetaRsltSn: number) => `${R}/${asmtSn}/analysis-data/${asmtMetaRsltSn}/review-close`,
  allStatusCheck: (asmtSn: number) => `${R}/${asmtSn}/analysis-data/all-status-check`,
  metaAccessCheck: (asmtSn: number) => `${R}/${asmtSn}/analysis-data/meta-access-check`,
  opinion: (asmtSn: number, asmtMetaRsltSn: number) => `${R}/${asmtSn}/analysis-data/${asmtMetaRsltSn}/opinion`,
  opinionFlat: (asmtSn: number) => `${R}/${asmtSn}/analysis-data/opinion`,
  files: (asmtSn: number) => `${R}/${asmtSn}/files`,
  irbFiles: (asmtSn: number) => `${R}/${asmtSn}/irb-files`,
  irbFileItem: (asmtSn: number, encodedAtchFileId: string) => `${R}/${asmtSn}/irb-files/${encodedAtchFileId}`,
  partnerFiles: (asmtSn: number) => `${R}/${asmtSn}/partner-files`,
  partnerFileItem: (asmtSn: number, encodedAtchFileId: string) => `${R}/${asmtSn}/partner-files/${encodedAtchFileId}`,
  adminFiles: (asmtSn: number) => `${R}/${asmtSn}/admin-files`,
  adminFileItem: (asmtSn: number, encodedAtchFileId: string) => `${R}/${asmtSn}/admin-files/${encodedAtchFileId}`,
  comments: (asmtSn: number) => `${R}/${asmtSn}/comments`,
  commentBySn: (asmtSn: number, asmtCmntSn: number) => `${R}/${asmtSn}/comments/${asmtCmntSn}`,
  accounts: () => `${R}/accounts`,
  accountsByAsmt: (asmtSn: number) => `${R}/${asmtSn}/accounts`,
  accountBySn: (sqAsmtAccountSn: number) => `${R}/accounts/${sqAsmtAccountSn}`,
  asmtPersonEmpOptions: () => `${R}/asmt-persons/emp-options`,
  asmtPersons: () => `${R}/asmt-persons`,
  asmtPersonBySn: (personSn: number) => `${R}/asmt-persons/${personSn}`,
  analysisDataset: (queryString: string) => `${R}/analysis-dataset?${queryString}`,
  analysisDatasetTask: (encodedTaskId: string) => `${R}/analysis-dataset/tasks/${encodedTaskId}`,
} as const;
